<?php

namespace ContainerN0AAu7L;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAgendaCrudControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Admin\AgendaCrudController' shared autowired service.
     *
     * @return \App\Controller\Admin\AgendaCrudController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/easycorp/easyadmin-bundle/src/Contracts/Controller/CrudControllerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/easycorp/easyadmin-bundle/src/Controller/AbstractCrudController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Admin/BaseCrudController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Admin/AgendaCrudController.php';

        $container->services['App\\Controller\\Admin\\AgendaCrudController'] = $instance = new \App\Controller\Admin\AgendaCrudController();

        $instance->setContainer(($container->privates['.service_locator.OkS5_e6'] ?? $container->load('get_ServiceLocator_OkS5E6Service'))->withContext('App\\Controller\\Admin\\AgendaCrudController', $container));

        return $instance;
    }
}
