<?php

namespace ContainerN0AAu7L;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAgendaSlotPatternService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.VC3EcGM.App\Entity\AgendaSlotPattern' shared service.
     *
     * @return \App\Entity\AgendaSlotPattern
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.VC3EcGM": it needs an instance of "App\\Entity\\AgendaSlotPattern" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
