<?php

namespace ContainerN0AAu7L;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHomeControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AeSTD60.App\Controller\HomeController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AeSTD60.App\\Controller\\HomeController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'wikiRepo' => ['privates', 'App\\Repository\\WikiPageRepository', 'getWikiPageRepositoryService', true],
            'tagRepo' => ['privates', 'App\\Repository\\LocationTagRepository', 'getLocationTagRepositoryService', true],
        ], [
            'wikiRepo' => 'App\\Repository\\WikiPageRepository',
            'tagRepo' => 'App\\Repository\\LocationTagRepository',
        ]))->withContext('App\\Controller\\HomeController::index()', $container);
    }
}
