<?php

namespace ContainerN0AAu7L;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllerpublicPageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.L70esrZ.App\Controller\UserController::publicPage()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.L70esrZ.App\\Controller\\UserController::publicPage()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userRepository' => ['privates', 'App\\Repository\\UtilisateursRepository', 'getUtilisateursRepositoryService', true],
            'messageRepository' => ['privates', 'App\\Repository\\MessageRepository', 'getMessageRepositoryService', true],
            'notificationRepository' => ['privates', 'App\\Repository\\NotificationRepository', 'getNotificationRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'userRepository' => 'App\\Repository\\UtilisateursRepository',
            'messageRepository' => 'App\\Repository\\MessageRepository',
            'notificationRepository' => 'App\\Repository\\NotificationRepository',
            'em' => '?',
        ]))->withContext('App\\Controller\\UserController::publicPage()', $container);
    }
}
