<?php

namespace ContainerN0AAu7L;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWikiControllerdeletePatternService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VC3EcGM.App\Controller\WikiController::deletePattern()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VC3EcGM.App\\Controller\\WikiController::deletePattern()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'pattern' => ['privates', '.errored..service_locator.VC3EcGM.App\\Entity\\AgendaSlotPattern', NULL, 'Cannot autowire service ".service_locator.VC3EcGM": it needs an instance of "App\\Entity\\AgendaSlotPattern" but this type has been excluded because it\'s a Doctrine entity.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'pattern' => 'App\\Entity\\AgendaSlotPattern',
            'em' => '?',
        ]))->withContext('App\\Controller\\WikiController::deletePattern()', $container);
    }
}
