<?php

namespace ContainerN0AAu7L;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWikiControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.riZAoLQ.App\Controller\WikiController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.riZAoLQ.App\\Controller\\WikiController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'page' => ['privates', '.errored..service_locator.riZAoLQ.App\\Entity\\WikiPage', NULL, 'Cannot autowire service ".service_locator.riZAoLQ": it needs an instance of "App\\Entity\\WikiPage" but this type has been excluded because it\'s a Doctrine entity.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'page' => 'App\\Entity\\WikiPage',
            'em' => '?',
        ]))->withContext('App\\Controller\\WikiController::delete()', $container);
    }
}
