<?php

namespace ContainerN0AAu7L;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWikiPage2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.E1zCA7B.App\Entity\WikiPage' shared service.
     *
     * @return \App\Entity\WikiPage
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.E1zCA7B": it needs an instance of "App\\Entity\\WikiPage" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
