<?php

namespace ContainerXygpzVZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAgendaBookingControllerbookService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.t4OeTGr.App\Controller\AgendaBookingController::book()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.t4OeTGr.App\\Controller\\AgendaBookingController::book()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'wikiRepo' => ['privates', 'App\\Repository\\WikiPageRepository', 'getWikiPageRepositoryService', true],
            'patternRepo' => ['privates', 'App\\Repository\\AgendaSlotPatternRepository', 'getAgendaSlotPatternRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'notificationService' => ['privates', 'App\\Service\\NotificationService', 'getNotificationServiceService', true],
        ], [
            'wikiRepo' => 'App\\Repository\\WikiPageRepository',
            'patternRepo' => 'App\\Repository\\AgendaSlotPatternRepository',
            'em' => '?',
            'notificationService' => 'App\\Service\\NotificationService',
        ]))->withContext('App\\Controller\\AgendaBookingController::book()', $container);
    }
}
