<?php

namespace ContainerXygpzVZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeleteAccountTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\DeleteAccountType' shared autowired service.
     *
     * @return \App\Form\DeleteAccountType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/DeleteAccountType.php';

        return $container->privates['App\\Form\\DeleteAccountType'] = new \App\Form\DeleteAccountType();
    }
}
