<?php

namespace ContainerXygpzVZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLocationTagService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.TEOQWzO.App\Entity\LocationTag' shared service.
     *
     * @return \App\Entity\LocationTag
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.TEOQWzO": it needs an instance of "App\\Entity\\LocationTag" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
