<?php

namespace ContainerXygpzVZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStimulus_HelperService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'stimulus.helper' shared service.
     *
     * @return \Symfony\UX\StimulusBundle\Helper\StimulusHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/stimulus-bundle/src/Helper/StimulusHelper.php';

        $a = ($container->privates['twig'] ?? $container->load('getTwigService'));

        if (isset($container->privates['stimulus.helper'])) {
            return $container->privates['stimulus.helper'];
        }

        return $container->privates['stimulus.helper'] = new \Symfony\UX\StimulusBundle\Helper\StimulusHelper($a);
    }
}
