<?php

namespace ContainerXygpzVZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTagControllercreateForumService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TEOQWzO.App\Controller\TagController::createForum()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TEOQWzO.App\\Controller\\TagController::createForum()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tag' => ['privates', '.errored..service_locator.TEOQWzO.App\\Entity\\LocationTag', NULL, 'Cannot autowire service ".service_locator.TEOQWzO": it needs an instance of "App\\Entity\\LocationTag" but this type has been excluded because it\'s a Doctrine entity.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'tag' => 'App\\Entity\\LocationTag',
            'em' => '?',
        ]))->withContext('App\\Controller\\TagController::createForum()', $container);
    }
}
