<?php

namespace ContainerXygpzVZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTagControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yrswtWr.App\Controller\TagController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yrswtWr.App\\Controller\\TagController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tag' => ['privates', '.errored..service_locator.yrswtWr.App\\Entity\\LocationTag', NULL, 'Cannot autowire service ".service_locator.yrswtWr": it needs an instance of "App\\Entity\\LocationTag" but this type has been excluded because it\'s a Doctrine entity.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'notificationService' => ['privates', 'App\\Service\\NotificationService', 'getNotificationServiceService', true],
        ], [
            'tag' => 'App\\Entity\\LocationTag',
            'em' => '?',
            'notificationService' => 'App\\Service\\NotificationService',
        ]))->withContext('App\\Controller\\TagController::show()', $container);
    }
}
