<?php

namespace ContainerXygpzVZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWikiPageTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\WikiPageType' shared autowired service.
     *
     * @return \App\Form\WikiPageType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/WikiPageType.php';

        return $container->privates['App\\Form\\WikiPageType'] = new \App\Form\WikiPageType();
    }
}
