<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWEphnAT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWEphnAT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWEphnAT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWEphnAT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWEphnAT\App_KernelDevDebugContainer([
    'container.build_hash' => 'WEphnAT',
    'container.build_id' => 'a589ee32',
    'container.build_time' => 1764280958,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWEphnAT');
