<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXygpzVZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXygpzVZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXygpzVZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXygpzVZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXygpzVZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'XygpzVZ',
    'container.build_id' => 'b684cd65',
    'container.build_time' => 1764292203,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXygpzVZ');
