<?php

namespace ContainerWEphnAT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLocationTagServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\LocationTagService' shared autowired service.
     *
     * @return \App\Service\LocationTagService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/LocationTagService.php';

        return $container->privates['App\\Service\\LocationTagService'] = new \App\Service\LocationTagService(($container->privates['App\\Repository\\LocationTagRepository'] ?? $container->load('getLocationTagRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->services['kernel'] ?? $container->get('kernel', 1)));
    }
}
