<?php

namespace ContainerWEphnAT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWikiCalendarSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventSubscriber\WikiCalendarSubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\WikiCalendarSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventSubscriber/WikiCalendarSubscriber.php';

        $a = ($container->services['router'] ?? self::getRouterService($container));

        if (isset($container->privates['App\\EventSubscriber\\WikiCalendarSubscriber'])) {
            return $container->privates['App\\EventSubscriber\\WikiCalendarSubscriber'];
        }

        return $container->privates['App\\EventSubscriber\\WikiCalendarSubscriber'] = new \App\EventSubscriber\WikiCalendarSubscriber(($container->privates['App\\Repository\\AgendaSlotPatternRepository'] ?? $container->load('getAgendaSlotPatternRepositoryService')), ($container->privates['App\\Repository\\AgendaRepository'] ?? $container->load('getAgendaRepositoryService')), $a);
    }
}
