<?php

namespace ContainerWEphnAT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWikiControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.E1zCA7B.App\Controller\WikiController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.E1zCA7B.App\\Controller\\WikiController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'wikiPage' => ['privates', '.errored..service_locator.E1zCA7B.App\\Entity\\WikiPage', NULL, 'Cannot autowire service ".service_locator.E1zCA7B": it needs an instance of "App\\Entity\\WikiPage" but this type has been excluded because it\'s a Doctrine entity.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'locationTagService' => ['privates', 'App\\Service\\LocationTagService', 'getLocationTagServiceService', true],
            'notificationService' => ['privates', 'App\\Service\\NotificationService', 'getNotificationServiceService', true],
        ], [
            'wikiPage' => 'App\\Entity\\WikiPage',
            'em' => '?',
            'locationTagService' => 'App\\Service\\LocationTagService',
            'notificationService' => 'App\\Service\\NotificationService',
        ]))->withContext('App\\Controller\\WikiController::show()', $container);
    }
}
